# from galaxy
- src: geerlingguy.security
  version: 1.5.0

- src: zzet.rbenv
  version: 3.0.0

- src: jdauphant.nginx
  version: v2.8.1

- src: https://github.com/coopdevs/certbot_nginx
  version: multiple-domains
  name: certbot_nginx

- src: oefenweb.swapfile
  version: v2.0.7
